Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from striplog import Striplog, Component

s = Striplog.from_csv(filename='/Users/matt/Downloads/moving_sand_% - real_data (1).csv')

s.plot(aspect=5)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstriplog[39;00m [38;5;28;01mimport[39;00m Striplog, Component
[0;32m----> 3[0m s [38;5;241m=[39m [43mStriplog[49m[38;5;241;43m.[39;49m[43mfrom_csv[49m[43m([49m[43mfilename[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m/Users/matt/Downloads/moving_sand_[39;49m[38;5;132;43;01m% - r[39;49;00m[38;5;124;43meal_data (1).csv[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      5[0m s[38;5;241m.[39mplot(aspect[38;5;241m=[39m[38;5;241m5[39m)

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/striplog/striplog.py:630[0m, in [0;36mStriplog.from_csv[0;34m(cls, filename, text, dlm, lexicon, points, include, exclude, remap, function, null, ignore, source, stop, fieldnames)[0m
[1;32m    628[0m     [38;5;28;01mif[39;00m source [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    629[0m         source [38;5;241m=[39m filename
[0;32m--> 630[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    631[0m         text [38;5;241m=[39m f[38;5;241m.[39mread()
[1;32m    633[0m source [38;5;241m=[39m source [38;5;129;01mor[39;00m [38;5;124m'[39m[38;5;124mCSV[39m[38;5;124m'[39m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/matt/Downloads/moving_sand_% - real_data (1).csv'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matt/Downloads/moving_sand_% - real_data (1).csv'

