Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from striplog import Striplog, Component

comps = [
    Component(properties={'lithology': 'sandstone'}),
    Component(properties={'lithology': 'siltstone'}),
    Component(properties={'lithology': 'shale'}),
]

s = Striplog.from_log(gr, basis=gr.basis, cutoff=[40, 100], components=comps)

s
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/numpy/core/fromnumeric.py:57[0m, in [0;36m_wrapfunc[0;34m(obj, method, *args, **kwds)[0m
[1;32m     56[0m [38;5;28;01mtry[39;00m:
[0;32m---> 57[0m     [38;5;28;01mreturn[39;00m [43mbound[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m     58[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m     59[0m     [38;5;66;03m# A TypeError occurs if the object does have such a method in its[39;00m
[1;32m     60[0m     [38;5;66;03m# class, but its signature is not identical to that of NumPy's. This[39;00m
[0;32m   (...)[0m
[1;32m     64[0m     [38;5;66;03m# Call _wrapit from within the except clause to ensure a potential[39;00m
[1;32m     65[0m     [38;5;66;03m# exception has a traceback chain.[39;00m

[0;31mTypeError[0m: '<' not supported between instances of 'Curve' and 'Curve'

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstriplog[39;00m [38;5;28;01mimport[39;00m Striplog, Component
[1;32m      3[0m comps [38;5;241m=[39m [
[1;32m      4[0m     Component(properties[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mlithology[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124msandstone[39m[38;5;124m'[39m}),
[1;32m      5[0m     Component(properties[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mlithology[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124msiltstone[39m[38;5;124m'[39m}),
[1;32m      6[0m     Component(properties[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mlithology[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mshale[39m[38;5;124m'[39m}),
[1;32m      7[0m ]
[0;32m----> 9[0m s [38;5;241m=[39m [43mStriplog[49m[38;5;241;43m.[39;49m[43mfrom_log[49m[43m([49m[43mgr[49m[43m,[49m[43m [49m[43mbasis[49m[38;5;241;43m=[39;49m[43mgr[49m[38;5;241;43m.[39;49m[43mbasis[49m[43m,[49m[43m [49m[43mcutoff[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;241;43m40[39;49m[43m,[49m[43m [49m[38;5;241;43m100[39;49m[43m][49m[43m,[49m[43m [49m[43mcomponents[49m[38;5;241;43m=[39;49m[43mcomps[49m[43m)[49m
[1;32m     11[0m s

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/striplog/striplog.py:1007[0m, in [0;36mStriplog.from_log[0;34m(cls, log, cutoff, components, legend, legend_field, field, right, basis, source)[0m
[1;32m   1005[0m [38;5;66;03m# Digitize.[39;00m
[1;32m   1006[0m [38;5;28;01mtry[39;00m:  [38;5;66;03m# To use cutoff as a list.[39;00m
[0;32m-> 1007[0m     a [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mdigitize[49m[43m([49m[43mlog[49m[43m,[49m[43m [49m[43mcutoff[49m[43m,[49m[43m [49m[43mright[49m[43m)[49m
[1;32m   1008[0m [38;5;28;01mexcept[39;00m [38;5;167;01mValueError[39;00m:  [38;5;66;03m# It's just a number.[39;00m
[1;32m   1009[0m     a [38;5;241m=[39m np[38;5;241m.[39mdigitize(log, [cutoff], right)

File [0;32m<__array_function__ internals>:180[0m, in [0;36mdigitize[0;34m(*args, **kwargs)[0m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/numpy/lib/function_base.py:5507[0m, in [0;36mdigitize[0;34m(x, bins, right)[0m
[1;32m   5505[0m     [38;5;28;01mreturn[39;00m [38;5;28mlen[39m(bins) [38;5;241m-[39m _nx[38;5;241m.[39msearchsorted(bins[::[38;5;241m-[39m[38;5;241m1[39m], x, side[38;5;241m=[39mside)
[1;32m   5506[0m [38;5;28;01melse[39;00m:
[0;32m-> 5507[0m     [38;5;28;01mreturn[39;00m [43m_nx[49m[38;5;241;43m.[39;49m[43msearchsorted[49m[43m([49m[43mbins[49m[43m,[49m[43m [49m[43mx[49m[43m,[49m[43m [49m[43mside[49m[38;5;241;43m=[39;49m[43mside[49m[43m)[49m

File [0;32m<__array_function__ internals>:180[0m, in [0;36msearchsorted[0;34m(*args, **kwargs)[0m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/numpy/core/fromnumeric.py:1387[0m, in [0;36msearchsorted[0;34m(a, v, side, sorter)[0m
[1;32m   1319[0m [38;5;129m@array_function_dispatch[39m(_searchsorted_dispatcher)
[1;32m   1320[0m [38;5;28;01mdef[39;00m [38;5;21msearchsorted[39m(a, v, side[38;5;241m=[39m[38;5;124m'[39m[38;5;124mleft[39m[38;5;124m'[39m, sorter[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m   1321[0m     [38;5;124;03m"""[39;00m
[1;32m   1322[0m [38;5;124;03m    Find indices where elements should be inserted to maintain order.[39;00m
[1;32m   1323[0m 
[0;32m   (...)[0m
[1;32m   1385[0m 
[1;32m   1386[0m [38;5;124;03m    """[39;00m
[0;32m-> 1387[0m     [38;5;28;01mreturn[39;00m [43m_wrapfunc[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43msearchsorted[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mv[49m[43m,[49m[43m [49m[43mside[49m[38;5;241;43m=[39;49m[43mside[49m[43m,[49m[43m [49m[43msorter[49m[38;5;241;43m=[39;49m[43msorter[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/numpy/core/fromnumeric.py:66[0m, in [0;36m_wrapfunc[0;34m(obj, method, *args, **kwds)[0m
[1;32m     57[0m     [38;5;28;01mreturn[39;00m bound([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m     58[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m     59[0m     [38;5;66;03m# A TypeError occurs if the object does have such a method in its[39;00m
[1;32m     60[0m     [38;5;66;03m# class, but its signature is not identical to that of NumPy's. This[39;00m
[0;32m   (...)[0m
[1;32m     64[0m     [38;5;66;03m# Call _wrapit from within the except clause to ensure a potential[39;00m
[1;32m     65[0m     [38;5;66;03m# exception has a traceback chain.[39;00m
[0;32m---> 66[0m     [38;5;28;01mreturn[39;00m [43m_wrapit[49m[43m([49m[43mobj[49m[43m,[49m[43m [49m[43mmethod[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/numpy/core/fromnumeric.py:43[0m, in [0;36m_wrapit[0;34m(obj, method, *args, **kwds)[0m
[1;32m     41[0m [38;5;28;01mexcept[39;00m [38;5;167;01mAttributeError[39;00m:
[1;32m     42[0m     wrap [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m---> 43[0m result [38;5;241m=[39m [38;5;28;43mgetattr[39;49m[43m([49m[43masarray[49m[43m([49m[43mobj[49m[43m)[49m[43m,[49m[43m [49m[43mmethod[49m[43m)[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m     44[0m [38;5;28;01mif[39;00m wrap:
[1;32m     45[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(result, mu[38;5;241m.[39mndarray):

[0;31mTypeError[0m: '<' not supported between instances of 'Curve' and 'Curve'
TypeError: '<' not supported between instances of 'Curve' and 'Curve'

